# Framework for running automated tests on OSB using Travis-CI, see https://github.com/OpenSourceBrain/osb-model-validation

dist: xenial

addons:
   apt:
     packages:
        - python-tk
        - python-lxml
        - python-tornado
        - python-tables
    

language: python
python: 
    - 2.7
    - 3.7


env:
    - OMV_ENGINE=jNeuroML
    - OMV_ENGINE=jNeuroML_NEURON
    - OMV_ENGINE=Brian2     # Python script runs with Brian2; should be just Python, but Brian2 engine is quick to set up...

install: 
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation
    - pip install numpy scipy # Why is this needed? Scipy doesn't seem to get installed correctly on trusty with addons above...
    - pip install tables # Ditto
    - pip install matplotlib # This is more because Matplotlib v2.x is required...

script:
    - omv all -V
    - omv list -V 
    - env
    
    
    
    

